addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-server-dev-10
language: ruby
cache: bundler
env:
  matrix:
  - DB=postgresql
  global:
  - secure: E9sTuJvCeycl7tCoF3xW8MJ/78ETB1Wg1H06S88jiEMKKp0wAmAjVlWDfD724npWj1fB3gwSepDOvz60/3sWFWPsEzKxa3jLUU66BwJZhNjq77WrOtY0Ji9xfbntFW9Ca08NQvJn+eVCHBzrhMRb2eJrRDaB02APhWc2mliRSiw+3vKP9gnvcSxi+7vmbexkVPA6kIyhi+0YEgjiHa9HnkzFnIVOr+5xK0tFsoUn5GrvY0hmgDwJflQ3RFEQkiEHwoMDja+t2nq5T5/VN8vQ8h0veH1hAJhdtVk7dSZ/gpv0zDr7r8AXXKEg9Cc6VViYqP/+BP7mXFtQrBnWy+41Zgodt/XpMK5XaTk13bnwVr270Vf6PeJY2HMNAtCQ/ce0IXvOGUBgq9+Xiihh5rMlNaOh317V2vkL3fcBLXFNmKkTK+apHfofuZRyKeQ86sazK6Jvj61ZgK5NTbtjVO83KGyk87XU1bOrJkPpO13vTX5E9SufBaEW7px0cl2e7DueCO9s4G0Y11JBqF3zWt78q5jDu8iCntBwUkJVPAFGeAvVswdbNrBsTybadrYVX8Gyq0oOUVolXb1/gCu4Nkr/Mgl4eCURVEetDXtPsBHMvmxgwR1AW/w15gHrxnH/khughFh0Z8L9c+pU2zmh4Jx6Eoc3lPpmO6ziJwvHyKkDoX0=
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
script:
- bundle exec rake db:test:prepare
- bundle exec rspec spec
services:
- redis-server
before_deploy:
- export APPLICATION_NAME=civis
- export DEPLOYENV=$(if [ "${TRAVIS_BRANCH}" == "staging" ]; then echo "staging";
  else echo "production"; fi)
- export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
- "./.rollbar.sh started"
- export DEPLOY_ID="$(while read -r line; do echo "$line"; done < ~/deploy_id_from_rollbar)"
deploy:
  matrix:
  - provider: cloud66
    redeployment_hook:
      secure: "XWxwX37phzxLQYdEXtidG6nSeATgG1YNIoFhkTYDLR+ISzzrAEeW+CBYls5sYqzGveM1gRWNSgxQmajvxbNwnErqzrGN8SUmTPJvDYdVpUtJkApl6fraWPeuS7Y9i38cs9CyMaNhA9S7MsFkFSGq/Dq1tCKQYysJZfdl8QZq0UsPJjky+HtV0Rr97l58YpzstotdrPc0CH8Z4fxVYwExgBuZKqNLwLooXll3DVYlmPFAUsD0gQTnJO283PtVl42grn0UFsPUKoJ51uJX3yhDuFESYXOUpX1dHw9fJtcqNG+uXMTEvDH+u8sE5n432atPacPHe9xhMe8TcM66C6s3/J1xvyb+gV54hre39lpMr6+4SVamHTMUQnDMQ8r7lihtPtCxGMV7sl1kkeOwjpoJqe30+hgpbWyitDnT9FEikVJv7BqLr1SzZU4Sr7pmMqUvtvAsKJJrTEyK/8F5ICRtOSAHWKleXQYH8NeBlqomHW4jppiPF65rQbA3ue2L4Vh7a+nPvSNbPn6JXnsK/Fj1PFbEHETH5Rr45fLklsUIkXIxWPhs2lQSu91/DMsHXvdmoIqwqMeJehWY0W7ruA4Aka3p+JRGFe0TWsq10IOAVIA7fKjAyN8BNCW70s+0xDATdA/8Mbw274Bf4zo1BpXkhOk2+et9fTjsBebOHjFwrxA="
    on:
      branch: staging
  - provider: cloud66
    redeployment_hook:
      secure: "ImmJz3ptIsyjQ7MfS0YqCzEwsyFB1MBHbQ1dEbp/LgCI3y1/ZZ02ftrH6OizAdkdh1kV0ulXI+Df0Ib6g23VOZqLwzbt3J7OoJ1qcZMYOIOE2L0yKs4r8kCidfPk2hzc9BaCKs1aU5NmQnNGF0lm5T2i6wHdUc1mNYXk11PTYM42W3ZGa3oUbgMhvEeqB1zlz+/yY5F2JMH20qzsZk/jbuVd2GKoN3qMqpf8e3as7Jk7UZ42qgpIDF9ynsRvD8B3ud5j7J+WEXyPEs8VaqbUZRSWFZ02I/Iu5JbR/ROaT9cO+JL6mhxkh570gAHr9NmwQ4z6Xl/OCvdAzrj/ZX1G890lqj0V/faSF6ZUdo3u/wyHhRTYEQt9YiGVkhawH37Xk7p28GTBdDHWcBJ1Kg/r8BaVQe8OD7UrKa6hn8xaA6NGVnHEugXEx1O+9OcEm9/dJKaHPkVhSJSDTh+OWop3aH6/QfZmfn7eAt0LBpazkEmarzR2W8wSXjijbx/qc0/keJHCBBbIlw04HMayAnkYnSy6QZZnTZP/ZPNdnx2WES7AveCOn4gOf0xVexYUyqozwtDEEhUY28xqjnmPGWGNCppTcZIn0Q4pD9hgipVa7wgLcKHGsBmDetjnQNaK+i7etwwxSsFVXVmS2MtAmulBdxr6LirWMwxakyPGizWcqTw="
    on:
      branch: master
after_deploy:
- "./.rollbar.sh succeeded"
branches:
  only:
  - master
  - staging
